#!/bin/bash
# One-time setup for a persistent Cloudflare named tunnel.
#
# This creates a reliable tunnel that doesn't depend on the flaky
# trycloudflare.com quick tunnel API. Once configured, the tunnel
# hostname is stable and reusable forever.
#
# Prerequisites:
#   - A Cloudflare account
#   - A domain managed by Cloudflare DNS (even a free one works)
#
# Usage:
#   ./scripts/setup_tunnel.sh <your-domain.com>
#
# Example:
#   ./scripts/setup_tunnel.sh example.com
#   -> Creates tunnel accessible at csui.example.com
#
# After setup, collect_data.py will automatically use the named tunnel.
# No more trycloudflare.com dependency!

set -e

TUNNEL_NAME="csui-tunnel"
SUBDOMAIN="csui"
CONFIG_DIR="$HOME/.cloudflared"
TUNNEL_CONFIG="$CONFIG_DIR/csui-config.yml"

# Color helpers
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "=============================================="
echo "  Cloudflare Named Tunnel Setup"
echo "=============================================="
echo ""

# Check domain argument
if [ -z "$1" ]; then
    echo -e "${RED}Error: Missing domain argument${NC}"
    echo ""
    echo "Usage: ./scripts/setup_tunnel.sh <your-domain.com>"
    echo ""
    echo "Example:"
    echo "  ./scripts/setup_tunnel.sh example.com"
    echo "  -> Creates tunnel at csui.example.com"
    echo ""
    echo "You need a domain managed by Cloudflare DNS."
    echo "A free Cloudflare account + free domain registrar works."
    exit 1
fi

DOMAIN="$1"
HOSTNAME="${SUBDOMAIN}.${DOMAIN}"

echo "Domain:    $DOMAIN"
echo "Hostname:  $HOSTNAME"
echo "Tunnel:    $TUNNEL_NAME"
echo ""

# Step 1: Login (if needed)
if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
    echo -e "${YELLOW}Step 1/4: Logging in to Cloudflare...${NC}"
    echo "  A browser window will open. Select your domain: $DOMAIN"
    echo ""
    cloudflared tunnel login
    echo ""
    if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
        echo -e "${RED}Login failed - cert.pem not created${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Logged in successfully${NC}"
else
    echo -e "${GREEN}Step 1/4: Already logged in (cert.pem exists)${NC}"
fi
echo ""

# Step 2: Create tunnel (if needed)
EXISTING=$(cloudflared tunnel list -o json 2>/dev/null | python3 -c "
import sys, json
tunnels = json.load(sys.stdin)
for t in tunnels:
    if t['name'] == '$TUNNEL_NAME' and not t.get('deleted_at'):
        print(t['id'])
        break
" 2>/dev/null || echo "")

if [ -n "$EXISTING" ]; then
    TUNNEL_ID="$EXISTING"
    echo -e "${GREEN}Step 2/4: Tunnel '$TUNNEL_NAME' already exists (ID: $TUNNEL_ID)${NC}"
else
    echo -e "${YELLOW}Step 2/4: Creating tunnel '$TUNNEL_NAME'...${NC}"
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(cloudflared tunnel list -o json 2>/dev/null | python3 -c "
import sys, json
tunnels = json.load(sys.stdin)
for t in tunnels:
    if t['name'] == '$TUNNEL_NAME' and not t.get('deleted_at'):
        print(t['id'])
        break
" 2>/dev/null)
    if [ -z "$TUNNEL_ID" ]; then
        echo -e "${RED}Failed to create tunnel${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Tunnel created (ID: $TUNNEL_ID)${NC}"
fi
echo ""

# Step 3: Route DNS
echo -e "${YELLOW}Step 3/4: Setting up DNS route ($HOSTNAME -> tunnel)...${NC}"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" 2>&1 || true
echo -e "${GREEN}✓ DNS route configured${NC}"
echo ""

# Step 4: Write config file
echo -e "${YELLOW}Step 4/4: Writing config file...${NC}"
CRED_FILE="$CONFIG_DIR/${TUNNEL_ID}.json"

cat > "$TUNNEL_CONFIG" << EOF
# Cloudflare Named Tunnel config for crowdsourcing-ui
# Generated by setup_tunnel.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Tunnel: $TUNNEL_NAME
# Hostname: $HOSTNAME
# Tunnel ID: $TUNNEL_ID

tunnel: $TUNNEL_ID
credentials-file: $CRED_FILE

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:9000
  - service: http_status:404
EOF

echo -e "${GREEN}✓ Config written to $TUNNEL_CONFIG${NC}"
echo ""

# Also save a simple reference file for collect_data.py to find
cat > "$CONFIG_DIR/csui-tunnel-info.json" << EOF
{
  "tunnel_name": "$TUNNEL_NAME",
  "tunnel_id": "$TUNNEL_ID",
  "hostname": "$HOSTNAME",
  "config_file": "$TUNNEL_CONFIG",
  "credentials_file": "$CRED_FILE",
  "created_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF

echo "=============================================="
echo -e "${GREEN}  Setup Complete!${NC}"
echo "=============================================="
echo ""
echo "Your tunnel URL: https://$HOSTNAME"
echo ""
echo "To test manually:"
echo "  cloudflared tunnel --config $TUNNEL_CONFIG run"
echo ""
echo "collect_data.py will now automatically use this named tunnel"
echo "instead of the unreliable quick tunnel API."
echo ""
echo "The tunnel config points to localhost:9000, which will be"
echo "updated at runtime to match the actual Flask port."
echo ""
